# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
